export default [
    {
      id: 34,
      title: "Pink & White Full Set",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/pinkwhite.jpg"),
    },
    {
      id: 35,
      title: "White Tips Full Set",
      desc: "A deluxe spa is a luxurious sanctuary that offers an extensive array of high-end services, such as hot stone massages, hydrotherapy, aromatherapy, and exotic body treatments, all designed to promote physical and mental rejuvenation.",
      price: "25.00",
      img: require("public/whitetip.png"),
    },
    {
      id: 36,
      title: "Color Full Set",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/color.jpg"),
    },
    {
      id: 37,
      title: "Polish Full Set",
      desc: "A deluxe spa is a luxurious sanctuary that offers an extensive array of high-end services, such as hot stone massages, hydrotherapy, aromatherapy, and exotic body treatments, all designed to promote physical and mental rejuvenation.",
      price: "25.00",
      img: require("public/polish1.jpg"),
    },
    {
      id: 38,
      title: "Dipping Full Set",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/dip.jpg"),
    },
    {
      id: 39,
      title: "Pink & White REFILL",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/pinkwhite.jpg"),
    },
    {
      id: 40,
      title: "White Tips REFILL",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/whitetip.png"),
    },
    {
      id: 41,
      title: "Color REFILL",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/color.jpg"),
    },
    {
      id: 42,
      title: "Polish REFILL",
      desc: "A regular spa promotes relaxation, reduces stress, and improves overall well-being through services like massages, facials, and body treatments. The atmosphere is peaceful with soothing music, dim lighting, and comfortable furnishings..",
      price: "$15.00",
      img: require("public/polish1.jpg"),
    },
    {
      id: 43,
      title: "Dipping REFILL",
      desc: "A deluxe spa is a luxurious sanctuary that offers an extensive array of high-end services, such as hot stone massages, hydrotherapy, aromatherapy, and exotic body treatments, all designed to promote physical and mental rejuvenation.",
      price: "25.00",
      img: require("public/dip.jpg"),
    }
  ];