
export default [
  {
    id: 201,
    title: "Eyebrows",
    desc: "Enhance your natural beauty with our eyebrow shaping and grooming service. Our expert technicians will create the perfect shape for your face using a combination of waxing and tweezing techniques. ",
    price: "$9.00",
    img: require("public/browwax.jpg"),
  },
  {
    id: 211,
    title: "Upper Lip",
    desc: "Say goodbye to unwanted upper lip hair with our quick and easy waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$6.00",
    img: require("public/lipwax.jpg"),
  },
  {
    id: 221,
    title: "Chin",
    desc: "Get rid of unwanted chin hair with our expert waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$7.00",
    img: require("public/chinwax.png"),
  },
  {
    id: 231,
    title: "Brow, Lip, & Chin",
    desc: "Enhance your natural beauty with our full face waxing service. This package includes eyebrow shaping, upper lip waxing, and chin waxing for a complete grooming experience.",
    price: "$20.00",
    img: require("public/facewax.png"),
  },
  {
    id: 241,
    title: "Full Face",
    desc: "Get ready for a special occasion or just treat yourself to our full face waxing service. This package includes eyebrow shaping, upper lip waxing, chin waxing, and additional hair removal from cheeks, forehead, and sideburns.",
    price: "$30.00",
    img: require("public/facewax.jpg"),
  },
  {
    id: 251,
    title: "Full Legs",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/legwax2.jpg"),
  },
  {
    id: 261,
    title: "Half Legs",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/legwax.png"),
  },
  {
    id: 21,
    title: "Full Arms",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/armwax.jpg"),
  },
  {
    id: 218,
    title: "Half Arms",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/armwax2.jpg"),
  },
  {
    id: 219,
    title: "Under Arms",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/underwax.png"),
  },
  {
    id: 130,
    title: "Bikini",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/bikiniwax.jpeg"),
  },
  {
    id: 31,
    title: "Brazilian Bikini",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/brazwax.jpg"),
  },
  {
    id: 312,
    title: "Full Back",
    desc: "Get silky smooth legs with our expert full leg waxing service. Our gentle wax formula will leave your skin feeling smooth and hair-free for weeks.",
    price: "$60.00",
    img: require("public/backwax.png"),
  }
];
